"""Добавлена авторизация

Revision ID: d8252ad9efe8
Revises: ce73ed4c303d
Create Date: 2025-09-01 08:50:48.556088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8252ad9efe8'
down_revision: Union[str, None] = 'ce73ed4c303d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('owner_id', sa.Integer(), nullable=False))
    op.drop_index(op.f('name'), table_name='projects')
    op.create_foreign_key(None, 'projects', 'users', ['owner_id'], ['id'])
    op.add_column('tasks', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tasks', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'owner_id')
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.create_index(op.f('name'), 'projects', ['name'], unique=True)
    op.drop_column('projects', 'owner_id')
    # ### end Alembic commands ###
